### ISSUE TITLE
Error authenticating against ADFS

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/plugin-dotcms-openSAML3#20]
While testing this plugin on a dEC environment for a client using ADFS as its IdP, we've been able to get dotCMS to redirect successfully to the IdP's login page; however, we are getting the following error after user and password are submitted:

```
[04/08/17 11:05:56:454 EDT] ERROR impl.SAMLSignatureProfileValidator: Apache xmlsec IdResolver could not resolve the Element for id reference: _ef29327e-f098-40f2-b016-724d9d06fdad\
[04/08/17 11:05:56:454 EDT] ERROR v3.SamlUtils: Apache xmlsec IdResolver could not resolve the Element for id reference: _ef29327e-f098-40f2-b016-724d9d06fdad\
org.opensaml.xmlsec.signature.support.SignatureException: Apache xmlsec IdResolver could not resolve the Element for id reference: _ef29327e-f098-40f2-b016-724d9d06fdad\
	at org.opensaml.saml.security.impl.SAMLSignatureProfileValidator.validateReferenceURI(SAMLSignatureProfileValidator.java:158) ~[opensaml-saml-impl-3.2.0.jar:?]\
	at org.opensaml.saml.security.impl.SAMLSignatureProfileValidator.validateSignatureImpl(SAMLSignatureProfileValidator.java:89) ~[opensaml-saml-impl-3.2.0.jar:?]\
	at org.opensaml.saml.security.impl.SAMLSignatureProfileValidator.validate(SAMLSignatureProfileValidator.java:63) ~[opensaml-saml-impl-3.2.0.jar:?]\
	at com.dotcms.plugin.saml.v3.SamlUtils.verifyAssertionSignature(SamlUtils.java:578) [SamlUtils.class:?]\
	at com.dotcms.plugin.saml.v3.handler.HttpPostAssertionResolverHandlerImpl.resolveAssertion(HttpPostAssertionResolverHandlerImpl.java:98) [HttpPostAssertionResolverHandlerImpl.class:?]\
	at com.dotcms.plugin.saml.v3.OpenSamlAuthenticationServiceImpl.resolveAssertion(OpenSamlAuthenticationServiceImpl.java:525) [OpenSamlAuthenticationServiceImpl.class:?]\
	at com.dotcms.plugin.saml.v3.OpenSamlAuthenticationServiceImpl.getUser(OpenSamlAuthenticationServiceImpl.java:198) [OpenSamlAuthenticationServiceImpl.class:?]\
	at com.dotcms.plugin.saml.v3.filter.SamlAccessFilter.autoLogin(SamlAccessFilter.java:512) [SamlAccessFilter.class:?]\
	at com.dotcms.plugin.saml.v3.filter.SamlAccessFilter.doFilter(SamlAccessFilter.java:288) [SamlAccessFilter.class:?]\
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]\
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]\
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]\
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]\
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]\
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]\
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]\
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]\
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]\
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]\
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]\
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]\
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]\
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]\
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]\
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]\
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]\
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]\
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]} 
```
Possible fix:
http://blog.samlsecurity.com/2014/05/exception-apache-xmlsec-idresolver.html

Full log and metadatafiles have been made available here to protect client's private information: https://my.dotcms.com/tickets/detail.dot?id=cf833c4e-0e89-4fea-bd85-390fdac67ddf

**Comment by gabbydotCMS** [comment]
Not a code issue.

Setting the following property on the ADFS side fixes the problem:
```
-SamlResponseSignature 'MessageAndAssertion'
```
The entire command looks something like this:

```
Set-ADFSRelyingPartyTrust -TargetIdentifier https://..... -Identifier https://.... -SamlResponseSignature 'MessageAndAssertion'
```

both TargetIdentifier and Identifier parameters are needed and must match what you have defined as Relying Party Identifiers

**Comment by jdotcms** [comment]
Cool, yeah the error is usually related to configuration
